CC = gcc
CFLAGS = -Wall -g
LDFLAGS = -L. -lksocket
PTHREAD = -lpthread

initksocket: initksocket.c ksocket.h
	$(CC) $(CFLAGS) initksocket.c -o initksocket $(PTHREAD) $(LDFLAGS)

clean:
	rm -f initksocket