CC = gcc
CFLAGS = -Wall -g
LDFLAGS = -L. -lksocket

all: user1 user2

user1: user1.c ksocket.h
	$(CC) $(CFLAGS) user1.c -o user1 $(LDFLAGS)

user2: user2.c ksocket.h
	$(CC) $(CFLAGS) user2.c -o user2 $(LDFLAGS)

clean:
	rm -f user1 user2 input.txt output.txt